version: ""

services:
  db:
    image: postgres:16
    container_name: ecsite-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecretpooppassword
      POSTGRES_DB: appdb
    ports:
      - "9999:8888"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
