services:
  db:
    image: postgres:16
    container_name: ecsite-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: appdb
    ports:
      - "9999:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecsite-api
    ports:
      - "8753:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - JWTSettings__Secret=${JWTSettings__Secret}
      - JWTSettings__ExpirationInMinutes=${JWTSettings__ExpirationInMinutes}
      - JWTSettings__Issuer=${JWTSettings__Issuer}
      - JWTSettings__Audience=${JWTSettings__Audience}
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
    depends_on:
      - db

volumes:
  pgdata:
