version: ""

services:
  db:
    image: postgres:16
    container_name: ecsite-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecretpooppassword
      POSTGRES_DB: appdb
    ports:
      - "9999:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  api:
    build: .
    container_name: ecsite-api
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=appdb;Username=postgres;Password=supersecretpooppassword
    depends_on:
      - db

volumes:
  pgdata:
